"""DESAFIO 031 - AULA 10
DESENVOLVA UM PROGRAMA QUE PERGUNTE A DISTANCIA DE UMA VIAGEM EM KM.

CALCULE O PRECO DA PASSAGEM, COBRANDO R$0,50 POR KM PARA VIAGENS DE ATE 200KM
E R$0,45 PARA VIAGENS MAIS LONGAS
"""